# Build.ps1 - Creates a self-contained PingUtility.exe
# This script embeds the HTA content into a PowerShell launcher and compiles to EXE

$ErrorActionPreference = "Stop"

$scriptDir = $PSScriptRoot
$htaPath = Join-Path $scriptDir "PingUtility.hta"
$launcherPath = Join-Path $scriptDir "PingUtility_Standalone.ps1"
$exePath = Join-Path $scriptDir "PingUtility.exe"

Write-Host "Building self-contained PingUtility.exe..." -ForegroundColor Cyan

# Read HTA content and encode as Base64
Write-Host "  Reading HTA file..."
$htaContent = Get-Content -Path $htaPath -Raw -Encoding UTF8
$htaBytes = [System.Text.Encoding]::UTF8.GetBytes($htaContent)
$htaBase64 = [Convert]::ToBase64String($htaBytes)

Write-Host "  HTA size: $($htaContent.Length) chars -> Base64: $($htaBase64.Length) chars"

# Create the standalone launcher script
Write-Host "  Generating standalone launcher..."

$launcherContent = @"
# PingUtility - Self-contained launcher
# Generated by Build.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

`$htaBase64 = @'
$htaBase64
'@

# Decode HTA content
`$htaBytes = [Convert]::FromBase64String(`$htaBase64)
`$htaContent = [System.Text.Encoding]::UTF8.GetString(`$htaBytes)

# Write to temp file
`$tempHta = "`$env:TEMP\PingUtility.hta"
[System.IO.File]::WriteAllText(`$tempHta, `$htaContent, [System.Text.Encoding]::UTF8)

# Launch and wait
`$process = Start-Process -FilePath "mshta.exe" -ArgumentList `$tempHta -PassThru
`$process.WaitForExit()

# Clean up
Remove-Item `$tempHta -Force -ErrorAction SilentlyContinue
"@

$launcherContent | Out-File -FilePath $launcherPath -Encoding UTF8

Write-Host "  Compiling to EXE..."

# Check if ps2exe is available
if (-not (Get-Command Invoke-PS2EXE -ErrorAction SilentlyContinue)) {
    Write-Host "  Installing ps2exe module..."
    Install-Module -Name ps2exe -Scope CurrentUser -Force
}

# Compile
Invoke-PS2EXE -InputFile $launcherPath `
              -OutputFile $exePath `
              -noConsole `
              -title "Ping Utility" `
              -description "Network connectivity monitoring tool" `
              -version "2.0.0.0"

# Clean up intermediate file
Remove-Item $launcherPath -Force

# Show result
$exeInfo = Get-Item $exePath
Write-Host ""
Write-Host "SUCCESS!" -ForegroundColor Green
Write-Host "  Output: $exePath"
Write-Host "  Size: $([math]::Round($exeInfo.Length / 1KB, 1)) KB"
Write-Host ""
Write-Host "This EXE is fully self-contained - no additional files needed!" -ForegroundColor Yellow

